name: desiderio/callback-request
typeName: desiderio_callbackrequest
title: 'Callback Request'
description: 'Callback Request captures visitor intent with focused form or request messaging. Editors can manage headline and copy fields and link and CTA controls.'
group: conversion
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 2
  -
    identifier: form_action
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:form_action'
  -
    identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
    default: 'Request callback'
