name: desiderio/how-to-steps
typeName: desiderio_howtosteps
title: 'How-to Steps'
description: 'How-to Steps helps visitors find their way through links, menus, anchors, or search entry points. Editors can manage headline and copy fields and repeatable entries.'
group: content
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    label: Introduction
    rows: 3
  -
    identifier: items
    type: Collection
    label: Steps
    minItems: 2
    fields:
      -
        identifier: title
        type: Textarea
        rows: 1
        label: 'Step Title'
        required: true
      -
        identifier: content
        type: Textarea
        label: 'Step Instructions'
        enableRichtext: true
        rows: 4
      -
        identifier: image
        type: File
        label: 'Step Image'
        allowed: common-image-types
        maxitems: 1
