name: desiderio/feature-image
typeName: desiderio_featureimage
title: 'Image Feature Section'
description: 'Image Feature Section explains product value, features, or use cases in a clear content structure. Editors can manage headline and copy fields, media pickers, link and CTA controls and layout or variant options.'
group: features
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: image
    type: File
    label: 'Feature Image'
    allowed: common-image-types
    maxitems: 1
  -
    identifier: image_position
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:image_position'
    items:
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.right'
        value: right
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.left'
        value: left
    default: right
  -
    identifier: link
    type: Link
    label: 'Call to Action Link'
  -
    identifier: link_text
    type: Textarea
    rows: 1
    label: 'Call to Action Text'
