name: desiderio/about-us
typeName: desiderio_aboutus
title: 'About the Company'
description: 'About the Company introduces people, roles, culture, or hiring context with clear editorial structure. Editors can manage headline and copy fields, media pickers and link and CTA controls.'
group: team
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 5
  -
    identifier: image
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:image'
    allowed: common-image-types
    maxitems: 1
  -
    identifier: cta_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: cta_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
