name: webconsulting/site-package-desiderio-corporate
label: "Site Package: Desiderio Corporate"
dependencies:
  - webconsulting/desiderio-content-elements
  - webconsulting/desiderio-preset-corporate
