name: webconsulting/site-package-desiderio-editorial
label: "Site Package: Desiderio Editorial"
dependencies:
  - webconsulting/desiderio-content-elements
  - webconsulting/desiderio-preset-editorial
