name: desiderio/chart-radar
typeName: desiderio_chartradar
title: 'Radar Chart'
description: 'Place the Radar Chart content element as a focused page section.'
group: data
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    enableRichtext: true
    richtextConfiguration: desiderio
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 2
  -
    identifier: axes
    type: Textarea
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/chart-radar/language/labels.xlf:field.axes'
    description: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/chart-radar/language/labels.xlf:field.axes.description'
    rows: 6
    required: true
  -
    identifier: series_name
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/chart-radar/language/labels.xlf:field.series_name'
    description: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/chart-radar/language/labels.xlf:field.series_name.description'
  -
    identifier: chart_data
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:chart_data_json'
    description: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/chart-radar/language/labels.xlf:field.chart_data.description'
    rows: 6
    required: true
  -
    identifier: fill_opacity
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:fill_opacity'
    items:
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.light'
        value: '0.15'
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.medium'
        value: '0.25'
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.strong'
        value: '0.4'
    default: '0.25'
