name: desiderio/product-feature
typeName: desiderio_productfeature
title: 'Product Feature Pricing'
description: 'Product Feature Pricing supports buying decisions with prices, plans, packages, or calculated options. Editors can manage headline and copy fields, media pickers, repeatable entries and link and CTA controls.'
group: pricing
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: image
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:product_image'
    allowed: common-image-types
    maxitems: 1
  -
    identifier: features
    type: Collection
    table: product_feature_features
    label: 'Feature Benefits'
    labelField: text
    minItems: 1
    maxItems: 8
    fields:
      -
        identifier: text
        type: Textarea
        rows: 1
        label: Feature
  -
    identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: button_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
