name: desiderio/cta-with-image
typeName: desiderio_ctawithimage
title: 'Image Call to Action'
description: 'Image Call to Action pairs media or embedded content with supporting editorial context. Editors can manage headline and copy fields, media pickers, link and CTA controls and layout or variant options.'
group: conversion
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: image
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:image'
    allowed: common-image-types
    maxitems: 1
  -
    identifier: cta_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: cta_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
  -
    identifier: image_position
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:image_position'
    items:
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.left'
        value: left
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.right'
        value: right
    default: right
