name: desiderio/counter
typeName: desiderio_counter
title: Counter
description: 'Counter presents performance numbers as a quick-read dashboard block. Editors can manage headline and copy fields, repeatable entries and layout or variant options.'
group: data
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: items
    type: Collection
    table: counter_items
    label: Counters
    minItems: 1
    fields:
      -
        identifier: target_value
        type: Number
        label: 'Target Value'
        required: true
      -
        identifier: prefix
        type: Textarea
        rows: 1
        label: Prefix
        description: 'e.g. $ or +'
      -
        identifier: suffix
        type: Textarea
        rows: 1
        label: Suffix
        description: 'e.g. %, K, M'
      -
        identifier: label
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:label_field'
        required: true
  -
    identifier: columns
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:columns'
    items:
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.2_columns'
        value: '2'
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.3_columns'
        value: '3'
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.4_columns'
        value: '4'
    default: '3'
