name: desiderio/back-to-top
typeName: desiderio_backtotop
title: 'Back to Top Button'
description: 'Back to Top Button helps visitors find their way through links, menus, anchors, or search entry points. Editors can manage headline and copy fields and layout or variant options.'
group: footer
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: label
    type: Textarea
    rows: 1
    label: 'Button Label'
    default: 'Back to top'
  -
    identifier: show_label
    type: Checkbox
    label: 'Show Label Text'
    default: 0
  -
    identifier: position
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:position'
    items:
      -
        label: 'Bottom Right'
        value: bottom-right
      -
        label: 'Bottom Left'
        value: bottom-left
      -
        label: 'Bottom Center'
        value: bottom-center
    default: bottom-right
