name: desiderio/testimonial-carousel
typeName: desiderio_testimonialcarousel
title: 'Carousel Testimonial'
description: 'Place the Carousel Testimonial content element as a focused page section.'
group: social-proof
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: autoplay
    type: Checkbox
    label: Autoplay
    default: 1
  -
    identifier: testimonials
    type: Relation
    allowed: desiderio_testimonial
    label: Testimonials
    minitems: 2
