name: desiderio/feature-minimal
typeName: desiderio_featureminimal
title: 'Minimal Feature Section'
description: 'Use when the minimal feature section should explain product value in a structured section.'
group: features
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:subheadline'
    rows: 2
  -
    identifier: items
    type: Collection
    table: feature_minimal_items
    prefixField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:features'
    minItems: 1
    fields:
      -
        identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:title'
        required: true
      -
        identifier: description_text
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:short_description'
