name: desiderio/job-card
typeName: desiderio_jobcard
title: 'Job Card'
description: 'Place the Job Card content element as a focused page section.'
group: team
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:job.title'
  -
    identifier: department
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:job.department'
  -
    identifier: location
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:job.location'
  -
    identifier: type
    type: Text
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:job.employment_type'
  -
    identifier: description
    type: Textarea
    enableRichtext: true
    richtextConfiguration: desiderio
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 4
  -
    identifier: apply_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:apply_link'
