name: desiderio/job-card
typeName: desiderio_jobcard
title: 'Job Card'
description: 'Job Card introduces people, roles, culture, or hiring context with clear editorial structure. Editors can manage headline and copy fields and link and CTA controls.'
group: team
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'Job Title'
  -
    identifier: department
    type: Textarea
    rows: 1
    label: Department
  -
    identifier: location
    type: Textarea
    rows: 1
    label: Location
  -
    identifier: type
    type: Text
    label: 'Employment Type'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 4
  -
    identifier: apply_link
    type: Link
    label: 'Apply Link'
