name: webconsulting/site-package-desiderio-portfolio
label: "Site Package: Desiderio Portfolio"
dependencies:
  - webconsulting/desiderio-content-elements
  - webconsulting/desiderio-preset-portfolio
