name: desiderio/header-page
typeName: desiderio_headerpage
title: 'Header Page'
description: 'Header Page helps visitors find their way through links, menus, anchors, or search entry points. Editors can manage headline and copy fields, link and CTA controls and layout or variant options.'
group: navigation
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: variant
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:alignment'
    items:
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.left'
        value: left
      -
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:item.center'
        value: center
    default: left
  -
    identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: button_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
