name: desiderio/cta-split
typeName: desiderio_ctasplit
title: 'Split Call to Action'
description: 'Present two side-by-side prompts, each with its own title, text, and button, to steer visitors down two paths.'
group: conversion
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: left_title
    type: Textarea
    rows: 1
    label: 'Left Title'
  -
    identifier: left_description
    type: Textarea
    enableRichtext: true
    richtextConfiguration: desiderio
    label: 'Left Description'
    rows: 2
  -
    identifier: left_button_text
    type: Textarea
    rows: 1
    label: 'Left Button Text'
  -
    identifier: left_button_link
    type: Link
    label: 'Left Button Link'
  -
    identifier: right_title
    type: Textarea
    rows: 1
    label: 'Right Title'
  -
    identifier: right_description
    type: Textarea
    enableRichtext: true
    richtextConfiguration: desiderio
    label: 'Right Description'
    rows: 2
  -
    identifier: right_button_text
    type: Textarea
    rows: 1
    label: 'Right Button Text'
  -
    identifier: right_button_link
    type: Link
    label: 'Right Button Link'
