name: desiderio/utility-bar
typeName: desiderio_utilitybar
title: 'Utility Bar'
description: 'Use when the utility bar should help visitors move through sections or pages.'
group: navigation
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: left_text
    type: Textarea
    rows: 1
    label: 'Left Text'
  -
    identifier: link_items
    type: Collection
    table: utility_bar_link_items
    prefixField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:links'
    fields:
      -
        identifier: label
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:label_field'
      -
        identifier: link
        type: Link
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link'
