name: desiderio/footer-app-links
typeName: desiderio_footerapplinks
title: 'App Links Footer'
description: 'App Links Footer closes a page with utility information, legal links, contact routes, or service details. Editors can manage headline and copy fields, media pickers and link and CTA controls.'
group: footer
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 2
  -
    identifier: appstore_link
    type: Link
    label: 'App Store Link'
  -
    identifier: playstore_link
    type: Link
    label: 'Google Play Link'
  -
    identifier: qr_image
    type: File
    label: 'QR Code Image'
    allowed: common-image-types
    maxitems: 1
  -
    identifier: copyright
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:copyright_text'
