services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Webconsulting\Desiderio\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/ViewHelpers/*'

  Webconsulting\Desiderio\ViewHelpers\:
    resource: '../Classes/ViewHelpers/*'
    tags:
      - name: fluid.viewhelper

  Webconsulting\Desiderio\DataProcessing\ContentBlockCollectionProcessor:
    tags:
      - name: data.processor
        identifier: desiderio-content-block-collections
