name: desiderio/stats-inline
typeName: desiderio_statsinline
title: 'Inline Stats'
description: 'Drop a couple of figures inline within running text.'
group: social-proof
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: show_separator
    type: Checkbox
    label: 'Show Separators'
    default: 1
  -
    identifier: stats
    type: Collection
    table: stats_inline_stats
    prefixField: true
    label: Stats
    minItems: 2
    fields:
      -
        identifier: value
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:value'
        required: true
      -
        identifier: label
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:label_field'
        required: true
