name: desiderio/pricing-enterprise
typeName: desiderio_pricingenterprise
title: 'Enterprise Pricing'
description: 'Use when the enterprise pricing should present costs or plan choices close to a decision.'
group: pricing
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: features
    type: Collection
    table: pricing_enterprise_features
    prefixField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:features'
    labelField: text
    minItems: 1
    maxItems: 8
    fields:
      -
        identifier: text
        type: Textarea
        rows: 1
        label: Feature
  -
    identifier: contact_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
    default: 'Contact Sales'
  -
    identifier: contact_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
  -
    identifier: image
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:image'
    allowed: common-image-types
    maxitems: 1
