name: desiderio/timeline
typeName: desiderio_timeline
title: 'Timeline'
description: 'Place the Timeline content element as a focused page section.'
group: content
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: subheadline
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:subheadline'
    rows: 2
  -
    identifier: items
    type: Collection
    table: timeline_items
    prefixField: true
    label: 'Timeline Items'
    minItems: 1
    fields:
      -
        identifier: step
        type: Textarea
        rows: 1
        label: 'Step / Date'
        required: true
      -
        identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:title'
        required: true
      -
        identifier: content
        type: Textarea
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:content'
        rows: 4
        enableRichtext: true
        richtextConfiguration: desiderio
      -
        identifier: link_text
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link_text'
      -
        identifier: link
        type: Link
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link'
