name: desiderio/cookie-banner
typeName: desiderio_cookiebanner
title: 'Cookie Consent Banner'
description: 'Place the Cookie Consent Banner content element as a focused page section.'
group: footer
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: content
    type: Textarea
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.content'
    description: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.content.description'
    enableRichtext: true
    richtextConfiguration: desiderio
    rows: 3
    required: true
  -
    identifier: accept_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.accept_text'
    default: 'Accept all'
  -
    identifier: decline_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.decline_text'
    default: Decline
  -
    identifier: settings_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.settings_text'
    default: 'Manage preferences'
  -
    identifier: settings_link
    type: Link
    label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.settings_link'
    description: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:field.settings_link.description'
  -
    identifier: position
    type: Select
    renderType: selectSingle
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:position'
    items:
      -
        label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:item.position.bottom'
        value: bottom
      -
        label: 'LLL:EXT:desiderio/ContentBlocks/ContentElements/cookie-banner/language/labels.xlf:item.position.top'
        value: top
    default: bottom
