<?php

declare(strict_types=1);

namespace Webconsulting\Desiderio\Tests\Unit;

use PHPUnit\Framework\Attributes\Test;
use PHPUnit\Framework\TestCase;

/**
 * Enforces the atomic-design layering of the Fluid component library and
 * the way content elements, page templates and extension template sets
 * compose it:
 *
 *  A1 layer graph: atoms use no molecules/organisms, molecules no organisms,
 *     layouts neither
 *  A2 organisms are composed only by page templates, presets and organisms
 *  A3 every content element renders through >= 1 d: component inside a
 *     d:layout.section root and renders no partials
 *  A4 no raw atomic markup (button/card/badge/heading signatures, inline SVG
 *     icons) outside the component library
 *  A5 the legacy Resources/Private/Partials/ directory stays gone
 *  A6 f:format.raw and f:cObject only where the allowlist documents why
 *
 * Reviewed exceptions live in Fixtures/atomic-allowlist.php with a reason;
 * an allowlist entry that no longer matches a finding fails the test.
 */
final class AtomicDesignConformanceTest extends TestCase
{
    private const string ROOT = __DIR__ . '/../..';
    private const string COMPONENTS = 'Resources/Private/Components';

    /** Content elements that are not sections (overlays, bars, footers): no d:layout.section root required. */
    private const array NON_SECTION_ELEMENTS = [
        'back-to-top', 'content-divider', 'cookie-banner', 'cta-floating', 'gdpr-banner', 'legal-links',
        'footer', 'footer-app-links', 'footer-brand', 'footer-columns', 'footer-contact', 'footer-dark',
        'footer-mega', 'footer-minimal', 'footer-newsletter', 'footer-social', 'footer-split',
    ];

    private const array RAW_SIGNATURES = [
        'button-like' => '/<(?:a|button)\b[^>]*\bclass="[^"]*\binline-flex\b[^"]*\brounded-md\b[^"]*\bfont-medium\b[^"]*"/',
        'card-like' => '/class="[^"]*\brounded-xl\b[^"]*\bbg-card\b[^"]*"/',
        'badge-like' => '/class="[^"]*\brounded-full\b[^"]*\btext-xs\b[^"]*\bfont-(?:medium|semibold)\b[^"]*"/',
        'heading-like' => '/<h[1-6]\b[^>]*\bclass="[^"]*\btext-(?:xl|2xl|3xl|4xl)\b[^"]*"/',
        'inline-svg' => '/<svg\b/',
    ];

    private const array FORMAT_RAW_ALLOWLIST = [
        'Resources/Private/ClassicContent/Templates/Generic.fluid.html' => '{content} is the TYPO3-rendered output of f:cObject (already HTML)',
        'Resources/Private/ClassicContent/Templates/BlogArchive.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/BlogAuthorposts.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/BlogCategory.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/BlogPosts.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/BlogTag.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/PowermailPi1.fluid.html' => '{content} is the TYPO3-rendered plugin output of f:cObject',
        'Resources/Private/ClassicContent/Templates/Html.fluid.html' => 'record.bodytext of the HTML element is editor-authored raw markup by definition',
        'Resources/Private/Templates/Pages/ElementPreview.fluid.html' => '{content} is the rendered content element (PAGEVIEW content area output)',
        'Resources/Private/Solr/Layouts/Split.html' => '{extraContent} is rendered HTML handed over by EXT:solr',
        'Resources/Private/Solr/Partials/Result/Document.html' => 'documentScoreAnalyze is the debug table generated by EXT:solr',
        'Resources/Private/Extensions/Powermail/Templates/Form/Confirmation.html' => 'powermail_all is the HTML summary rendered by EXT:powermail',
        'Resources/Private/Extensions/Powermail/Partials/Form/Field/Html.html' => 'field.text is wrapped in f:sanitize.html',
        'Resources/Private/Extensions/News/Partials/Detail/StructuredData.html' => 'JSON-LD script body; escaping would break the JSON',
        'Resources/Private/Extensions/Blog/Partials/Meta/Rendering/Group.html' => '{content} is the output of the EXT:blog meta ViewHelpers (already HTML)',
        'Resources/Private/Extensions/Blog/Partials/Meta/Rendering/Item.html' => 'icon, prefix and content are EXT:blog meta ViewHelper output (already HTML)',
        'Resources/Private/Form/Email/Layouts/SystemEmail.fluid.html' => 'typo3.information.copyrightNotice is core-provided HTML',
        'Resources/Private/Form/Email/Templates/Default.fluid.txt' => 'plain-text mail: processedValue must not be HTML-escaped',
        'ContentBlocks/ContentElements/alert/templates/frontend.html' => 'alertInner is captured, already-escaped Fluid output',
        'ContentBlocks/ContentElements/notification/templates/frontend.html' => 'notificationInner is captured, already-escaped Fluid output',
        'Resources/Private/Components/Molecule/SectionIntro/SectionIntro.fluid.html' => 'slot content captured into a variable is already-escaped Fluid output',
        'Resources/Private/Components/Molecule/FeatureItem/FeatureItem.fluid.html' => 'slot content captured into a variable is already-escaped Fluid output',
        'Resources/Private/Components/Molecule/Figure/Figure.fluid.html' => 'slot content captured into a variable is already-escaped Fluid output',
        'Resources/Private/Components/Molecule/Stat/Stat.fluid.html' => 'slot content captured into a variable is already-escaped Fluid output',
    ];

    /** @var array<string, array<string, string>>|null */
    private static ?array $allowlist = null;

    /** @var array<string, array<string, true>> path => rule => matched */
    private static array $allowlistHits = [];

    public static function tearDownAfterClass(): void
    {
        $unused = [];
        foreach (self::allowlist() as $path => $rules) {
            foreach (array_keys($rules) as $rule) {
                if (!isset(self::$allowlistHits[$path][$rule])) {
                    $unused[] = $path . ' [' . $rule . ']';
                }
            }
        }
        self::assertSame([], $unused, 'Allowlist entries that no longer match a finding must be removed');
    }

    #[Test]
    public function a1LayerGraphIsRespected(): void
    {
        $violations = [];
        $forbidden = [
            'Atom' => ['<d:molecule.', '<d:organism.', '{d:molecule.', '{d:organism.'],
            'Molecule' => ['<d:organism.', '{d:organism.'],
            'Layout' => ['<d:molecule.', '<d:organism.', '{d:molecule.', '{d:organism.'],
        ];
        foreach ($forbidden as $layer => $needles) {
            foreach ($this->files(self::COMPONENTS . '/' . $layer) as $path => $source) {
                foreach ($needles as $needle) {
                    if (str_contains($source, $needle)) {
                        $violations[] = $this->finding($path, 'A1', sprintf('%s uses %s', $layer, $needle));
                    }
                }
            }
        }
        $this->assertNoViolations($violations);
    }

    #[Test]
    public function a2OrganismsAreOnlyComposedByPageLevelTemplates(): void
    {
        $violations = [];
        $allowedPrefixes = [
            'Resources/Private/Templates/',
            'Resources/Private/Presets/',
            'Resources/Private/ShadcnUi/',
            'Resources/Private/Components/Organism/',
        ];
        foreach ($this->templateFiles() as $path => $source) {
            if (!str_contains($source, '<d:organism.') && !str_contains($source, '{d:organism.')) {
                continue;
            }
            foreach ($allowedPrefixes as $prefix) {
                if (str_starts_with($path, $prefix)) {
                    continue 2;
                }
            }
            $violations[] = $this->finding($path, 'A2', 'organism used outside page-level templates');
        }
        $this->assertNoViolations($violations);
    }

    #[Test]
    public function a3ContentElementsComposeComponentsInsideASectionRoot(): void
    {
        $violations = [];
        $elements = glob(self::ROOT . '/ContentBlocks/ContentElements/*/templates/frontend.html');
        self::assertIsArray($elements);
        self::assertGreaterThan(200, count($elements));
        foreach ($elements as $absolute) {
            $path = $this->relative($absolute);
            $element = basename(dirname($absolute, 2));
            $source = $this->stripComments((string)file_get_contents($absolute));
            if (preg_match('/<d:[a-z]+\.[a-zA-Z]+/', $source) !== 1) {
                $violations[] = $this->finding($path, 'A3', 'uses no d: component');
            }
            if (!in_array($element, self::NON_SECTION_ELEMENTS, true) && !str_contains($source, '<d:layout.section')) {
                $violations[] = $this->finding($path, 'A3', 'has no d:layout.section root');
            }
            if (preg_match('/f:render\b[^>]*\bpartial\s*[=:]/', $source) === 1) {
                $violations[] = $this->finding($path, 'A3', 'renders a partial; compose components instead');
            }
        }
        $this->assertNoViolations($violations);
    }

    #[Test]
    public function a4NoRawAtomicMarkupOutsideTheComponentLibrary(): void
    {
        $violations = [];
        foreach ($this->templateFiles() as $path => $source) {
            if (str_starts_with($path, self::COMPONENTS . '/')) {
                continue;
            }
            $source = $this->stripComments($source);
            foreach (self::RAW_SIGNATURES as $signature => $pattern) {
                if (preg_match($pattern, $source) !== 1) {
                    continue;
                }
                $violations[] = $this->finding($path, 'A4', $signature);
            }
        }
        $this->assertNoViolations($violations);
    }

    #[Test]
    public function a5LegacyPartialsDirectoryDoesNotExist(): void
    {
        self::assertDirectoryDoesNotExist(self::ROOT . '/Resources/Private/Partials', 'Resources/Private/Partials/ was never wired into a partialRootPath; use components');
    }

    #[Test]
    public function a6FormatRawUsesAreAllowlisted(): void
    {
        $violations = [];
        $seen = [];
        foreach ($this->templateFiles() as $path => $source) {
            if (preg_match('/f:format\.raw\b/', $this->stripComments($source)) !== 1) {
                continue;
            }
            $seen[$path] = true;
            if (!isset(self::FORMAT_RAW_ALLOWLIST[$path])) {
                $violations[] = $path . ': f:format.raw without a documented reason';
            }
        }
        self::assertSame([], $violations);
        self::assertSame([], array_values(array_diff(array_keys(self::FORMAT_RAW_ALLOWLIST), array_keys($seen))), 'f:format.raw allowlist entries without a use must be removed');
    }

    #[Test]
    public function a6CObjectPathsExist(): void
    {
        $typoScript = '';
        foreach ($this->files('Configuration/Sets', '/\.typoscript$/') as $source) {
            $typoScript .= $source . "\n";
        }
        $violations = [];
        foreach ($this->templateFiles() as $path => $source) {
            if (preg_match_all('/f:cObject\b[^>]*\btyposcriptObjectPath\s*=\s*"([^"]+)"/', $this->stripComments($source), $matches) < 1) {
                continue;
            }
            foreach ($matches[1] as $objectPath) {
                if (str_contains($objectPath, '{')) {
                    // Dynamic path (tt_content.{CType}.20, {widget}, {field.path}): resolved at runtime from tt_content/lib/plugin.
                    $static = (string)preg_replace('/\{[^}]*\}.*$/', '', $objectPath);
                    if ($static === '' || str_starts_with($static, 'lib.') || str_starts_with($static, 'tt_content.') || str_starts_with($static, 'plugin.')) {
                        continue;
                    }
                    $violations[] = $path . ': dynamic path "' . $objectPath . '" is not rooted in lib./tt_content./plugin.';
                    continue;
                }
                if (str_starts_with($objectPath, 'tt_content.') || str_starts_with($objectPath, 'lib.tx_news.') || str_starts_with($objectPath, 'lib.blog.') || str_starts_with($objectPath, 'plugin.tx_solr_')) {
                    // Registered by EXT:news / EXT:blog / EXT:solr or the content rendering definition.
                    continue;
                }
                $root = explode('.', $objectPath, 2)[0] === 'lib' ? explode(' ', explode('.', $objectPath, 3)[1] ?? '')[0] : '';
                $definition = 'lib.' . $root;
                if (preg_match('/^' . preg_quote($definition, '/') . '\s*(?:=|=<|\{)/m', $typoScript) !== 1) {
                    $violations[] = $path . ': "' . $objectPath . '" is not defined in Configuration/Sets/**/*.typoscript';
                }
            }
        }
        self::assertSame([], $violations);
    }

    /**
     * @param list<string> $violations
     */
    private function assertNoViolations(array $violations): void
    {
        self::assertSame([], array_values(array_filter($violations, static fn(string $violation): bool => $violation !== '')));
    }

    /**
     * Records a violation unless the allowlist covers it; returns '' when allowlisted.
     */
    private function finding(string $path, string $rule, string $detail): string
    {
        $allowlist = self::allowlist();
        if (isset($allowlist[$path][$rule])) {
            self::$allowlistHits[$path][$rule] = true;
            return '';
        }
        return $path . ' [' . $rule . '] ' . $detail;
    }

    /**
     * @return array<string, array<string, string>>
     */
    private static function allowlist(): array
    {
        if (self::$allowlist === null) {
            $allowlist = require __DIR__ . '/Fixtures/atomic-allowlist.php';
            self::assertIsArray($allowlist);
            /** @var array<string, array<string, string>> $allowlist */
            self::$allowlist = $allowlist;
        }
        return self::$allowlist;
    }

    /**
     * Every Fluid template of the extension keyed by relative path.
     *
     * @return array<string, string>
     */
    private function templateFiles(): array
    {
        $files = [];
        foreach (['ContentBlocks', 'Resources/Private'] as $directory) {
            $files += $this->files($directory, '/\.(?:html|fluid\.txt)$/');
        }
        ksort($files);
        return $files;
    }

    /**
     * @return array<string, string> relative path => source
     */
    private function files(string $directory, string $pattern = '/\.html$/'): array
    {
        $absoluteDirectory = self::ROOT . '/' . $directory;
        if (!is_dir($absoluteDirectory)) {
            return [];
        }
        $files = [];
        $iterator = new \RecursiveIteratorIterator(new \RecursiveDirectoryIterator($absoluteDirectory, \FilesystemIterator::SKIP_DOTS));
        foreach ($iterator as $file) {
            if (!$file instanceof \SplFileInfo || !$file->isFile() || preg_match($pattern, $file->getFilename()) !== 1) {
                continue;
            }
            $files[$this->relative($file->getPathname())] = (string)file_get_contents($file->getPathname());
        }
        return $files;
    }

    private function relative(string $absolute): string
    {
        $root = realpath(self::ROOT);
        self::assertIsString($root);
        return ltrim(str_replace($root, '', (string)realpath($absolute)), '/');
    }

    private function stripComments(string $source): string
    {
        return (string)preg_replace('/<f:comment>.*?<\/f:comment>|<!--.*?-->/s', '', $source);
    }
}
