name: desiderio/resource-library
typeName: desiderio_resourcelibrary
title: 'Resource Library'
description: 'Resource Library arranges multiple pieces of content as scannable cards, grids, or libraries. Editors can manage headline and copy fields and repeatable entries.'
group: content
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: items
    type: Collection
    table: resource_library_items
    label: Resources
    minItems: 1
    fields:
      -
        identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:title'
      -
        identifier: type_label
        type: Textarea
        rows: 1
        label: Type
      -
        identifier: description
        type: Textarea
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
        rows: 2
      -
        identifier: link
        type: Link
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link'
