name: desiderio/navbar-tabbed
typeName: desiderio_navbartabbed
title: 'Tabbed Navigation Bar'
description: 'Tabbed Navigation Bar helps visitors find their way through links, menus, anchors, or search entry points. Editors can manage headline and copy fields, repeatable entries and link and CTA controls.'
group: navigation
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: brand
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:brand'
    required: true
  -
    identifier: tabs
    type: Collection
    label: Tabs
    minItems: 1
    fields:
      -
        identifier: label
        type: Textarea
        rows: 1
        label: 'Tab Label'
      -
        identifier: link
        type: Link
        label: 'Tab Link'
      -
        identifier: active
        type: Checkbox
        label: Active
  -
    identifier: button_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: button_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
