name: desiderio/cta-minimal
typeName: desiderio_ctaminimal
title: CTA Minimal
description: Minimal text-only call to action with a single link
group: conversion
prefixFields: false
fields:
  - identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  - identifier: description_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
  - identifier: cta_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link_text'
  - identifier: cta_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:link'
