name: desiderio/feature-checklist
typeName: desiderio_featurechecklist
title: 'Checklist Feature Section'
description: 'A shadcn/ui styled TYPO3 content element for feature section, using theme tokens for light and dark mode.'
group: features
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: items
    type: Collection
    label: Checklist
    minItems: 1
    fields:
      -
        identifier: title
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:title'
      -
        identifier: description_text
        type: Textarea
        rows: 1
        label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
