name: desiderio/feature-video
typeName: desiderio_featurevideo
title: 'Video Feature Section'
description: 'Place the Video Feature Section content element as a focused page section.'
group: features
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: eyebrow
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:eyebrow'
  -
    identifier: description
    type: Textarea
    enableRichtext: true
    richtextConfiguration: desiderio
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: video_url
    type: Text
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:video_url'
    description: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:video_url.description'
  -
    identifier: video_file
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:video_file'
    allowed: common-media-types
    maxitems: 1
  -
    identifier: poster
    type: File
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:poster_image'
    allowed: common-image-types
    maxitems: 1
