name: desiderio/cta-gradient
typeName: desiderio_ctagradient
title: 'Gradient Call to Action'
description: 'Gradient Call to Action provides a focused editorial building block for a recognizable page task. Editors can manage headline and copy fields and link and CTA controls.'
group: conversion
prefixFields: false
basics:
  - TYPO3/Appearance
  - TYPO3/Links
  - TYPO3/Categories
fields:
  -
    identifier: header
    useExistingField: true
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:heading'
  -
    identifier: description
    type: Textarea
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:description'
    rows: 3
  -
    identifier: cta_text
    type: Textarea
    rows: 1
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_text'
  -
    identifier: cta_link
    type: Link
    label: 'LLL:EXT:desiderio/Resources/Private/Language/labels.xlf:button_link'
